apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
data:
  PORT: "3003"
  MONGODB_URI: "mongodb+srv://mlal:3BSB93stD1II4HF7@mlal-b1.vf0r1ta.mongodb.net/ecommerce_carts"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: munisekar/cart-service:latest
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: cart-service-config
          env:
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - port: 3003
      targetPort: 3003
