apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  PORT: "3002"
  MONGODB_URI: "mongodb+srv://mlal:3BSB93stD1II4HF7@mlal-b1.vf0r1ta.mongodb.net/ecommerce_products"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: nishmohan/product-service:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: product-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 3002
      targetPort: 3002
